name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      # 初始解压目录名；后面脚本会自动修正为真正含 pubspec.yaml 的目录
      PROJECT_DIR: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 选择仓库里“最后一次提交改动”的 zip（根目录或任意路径均可）
      - name: Pick latest ZIP in repo by last commit time
        id: pickzip
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t FILES < <(git ls-files '*.zip')
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "❌ No zip files found in repo."
            exit 1
          fi
          latest=""
          latest_ts=0
          for f in "${FILES[@]}"; do
            ts=$(git log -1 --format=%ct -- "$f" || echo 0)
            if (( ts > latest_ts )); then latest_ts=$ts; latest="$f"; fi
          done
          echo "LATEST_ZIP=$latest" >> "$GITHUB_ENV"
          echo "Picked latest zip: $latest"

      - name: Install unzip tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip p7zip-full

      - name: Unzip project
        shell: bash
        run: |
          set -euo pipefail
          rm -rf "$PROJECT_DIR"
          mkdir -p "$PROJECT_DIR"
          unzip -q "$LATEST_ZIP" -d "$PROJECT_DIR" || 7z x "$LATEST_ZIP" -o"$PROJECT_DIR" -y >/dev/null
          # 自动定位真正包含 pubspec.yaml 的目录
          if [ ! -f "$PROJECT_DIR/pubspec.yaml" ]; then
            inner=$(find "$PROJECT_DIR" -maxdepth 4 -type f -name pubspec.yaml | head -n1 || true)
            if [ -z "$inner" ]; then
              echo "❌ pubspec.yaml not found after unzip"
              find "$PROJECT_DIR" -maxdepth 4 -print
              exit 1
            fi
            realdir=$(dirname "$inner")
            echo "PROJECT_DIR=$realdir" >> "$GITHUB_ENV"
          else
            echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"
          fi
          echo "Resolved PROJECT_DIR=${PROJECT_DIR}"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter 3.22.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: stable
          cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Accept Android licenses (robust)
        shell: bash
        run: |
          set +e
          set +o pipefail
          yes | sdkmanager --licenses >/dev/null 2>&1
          code=$?
          # 0=正常，141=SIGPIPE，均视为成功
          if [ $code -ne 0 ] && [ $code -ne 141 ]; then
            echo "sdkmanager --licenses returned $code" >&2
            exit $code
          fi
          echo "Android licenses accepted (code=$code)."

      - name: Write android/local.properties
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -euo pipefail
          FLUTTER_BIN="$(which flutter)"
          FLUTTER_SDK="$(dirname "$(dirname "$(readlink -f "$FLUTTER_BIN")")")"
          mkdir -p android
          {
            printf "sdk.dir=%s\n" "$ANDROID_SDK_ROOT"
            printf "flutter.sdk=%s\n" "$FLUTTER_SDK"
          } > android/local.properties
          echo "== local.properties ==" && cat android/local.properties

      - name: Sanity check (android gradle files)
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          test -f pubspec.yaml
          test -f android/settings.gradle
          test -f android/app/build.gradle
          echo "OK: basic files present."

      - name: Flutter clean & pub get
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Build release APK
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
         set -euxo pipefail
         flutter --version
         flutter build apk --release -v
         echo "== Search for any produced APKs =="
         find . -maxdepth 8 -type f -name "*.apk" -print || true
         FOUND=$(find . -maxdepth 8 -type f -name "*.apk" | head -n1 || true)
         if [ -n "$FOUND" ]; then
         mkdir -p build/app/outputs/flutter-apk
         cp "$FOUND" build/app/outputs/flutter-apk/app-release.apk || true
         echo "Salvaged APK -> build/app/outputs/flutter-apk/"
         else
         echo "No APK files found after build." >&2
         exit 1
          fi

      - name: Show APK outputs
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          echo "== APK outputs =="
          ls -la build/app/outputs || true
          ls -la build/app/outputs/flutter-apk || true
          ls -la build/app/outputs/apk/release || true
          ls -la android/app/build/outputs/flutter-apk || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/*.apk
            ${{ env.PROJECT_DIR }}/build/app/outputs/apk/release/*.apk
            ${{ env.PROJECT_DIR }}/android/app/build/outputs/flutter-apk/*.apk
          if-no-files-found: warn
