name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter 3.22.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: stable
          cache: true

      # 选出仓库里最近一次提交过的 zip
      - name: Pick latest ZIP in repo by last commit time
        id: pickzip
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t FILES < <(git ls-files '*.zip')
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "❌ No zip files found."
            exit 1
          fi
          latest=""
          latest_ts=0
          for f in "${FILES[@]}"; do
            ts=$(git log -1 --format=%ct -- "$f" || echo 0)
            if (( ts > latest_ts )); then latest_ts=$ts; latest="$f"; fi
          done
          echo "LATEST_ZIP=$latest" >> "$GITHUB_ENV"
          echo "Picked: $latest"

      - name: Install unzip tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip p7zip-full

      - name: Unzip project
        shell: bash
        run: |
          set -euo pipefail
          rm -rf "$PROJECT_DIR"
          mkdir -p "$PROJECT_DIR"
          unzip -q "$LATEST_ZIP" -d "$PROJECT_DIR" || 7z x "$LATEST_ZIP" -o"$PROJECT_DIR" -y >/dev/null
          if [ ! -f "$PROJECT_DIR/pubspec.yaml" ]; then
            inner=$(find "$PROJECT_DIR" -maxdepth 3 -type f -name pubspec.yaml | head -n1 || true)
            if [ -z "$inner" ]; then
              echo "❌ pubspec.yaml not found after unzip"
              find "$PROJECT_DIR" -maxdepth 3 -print
              exit 1
            fi
            realdir=$(dirname "$inner")
            echo "PROJECT_DIR=$realdir" >> "$GITHUB_ENV"
          else
            echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"
          fi
          echo "Resolved PROJECT_DIR=${PROJECT_DIR}"

      # 放到解压之后，确保能命中 Gradle 缓存文件
      - name: Setup Java 17 (with Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
          cache-dependency-path: |
            ${{ env.PROJECT_DIR }}/**/*.gradle*
            ${{ env.PROJECT_DIR }}/**/gradle-wrapper.properties
            ${{ env.PROJECT_DIR }}/gradle/libs.versions.toml
            ${{ env.PROJECT_DIR }}/**/versions.properties

      - name: Setup Android SDK (cmdline-tools only)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708

      - name: Detect compileSdk/buildTools from project
        id: detect
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -euo pipefail
          COMPILE=$(grep -RhoP "compileSdk(?:Version)?\s*=?\s*\K\d+" android/app/build.gradle android/build.gradle || echo 34)
          BT=$(grep -RhoP "buildToolsVersion\s*['\"]\K[\d.]+" android/app/build.gradle android/build.gradle || echo 34.0.0)
          echo "COMPILE_SDK=$COMPILE" >> "$GITHUB_ENV"
          echo "BUILD_TOOLS=$BT" >> "$GITHUB_ENV"
          echo "Detected compileSdk=$COMPILE, buildTools=$BT"

      - name: Install Android packages via sdkmanager
        shell: bash
        run: |
          set -euo pipefail
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "build-tools;${BUILD_TOOLS}" \
            "platforms;android-${COMPILE_SDK}"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses >/dev/null

      - name: Write android/local.properties
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          set -euo pipefail
          FLUTTER_BIN="$(which flutter)"
          FLUTTER_SDK="$(dirname "$(dirname "$(readlink -f "$FLUTTER_BIN")")")"
          mkdir -p android
          {
            printf "sdk.dir=%s\n" "$ANDROID_SDK_ROOT"
            printf "flutter.sdk=%s\n" "$FLUTTER_SDK"
          } > android/local.properties
          cat android/local.properties

      - name: Quick sanity check (android gradle files)
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          test -f pubspec.yaml
          test -f android/settings.gradle
          test -f android/app/build.gradle

      - name: Flutter clean & pub get
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Build release APK
        shell: bash
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          flutter build apk --release
          ls -la build/app/outputs/flutter-apk || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: warn
