name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check - list repo root
        run: ls -lah

      - name: Pick latest ZIP (prefer root tracked; robust fallbacks)
        id: pickzip
        shell: bash
        run: |
          set -euo pipefail
          cd "$GITHUB_WORKSPACE"

          ROOT_TRACKED="$(git ls-files --full-name | awk '/^[^\/]+\.zip$/ {print}' || true)"

          pick_by_git_commit() {
            printf "%s\n" "$1" | while IFS= read -r f; do
              [ -n "$f" ] || continue
              ct="$(git log -1 --format=%ct -- "$f" 2>/dev/null || echo 0)"
              printf "%s %s\n" "$ct" "$f"
            done | sort -nr | head -n1 | cut -d' ' -f2-
          }

          SEL=""
          if [ -n "${ROOT_TRACKED:-}" ]; then
            SEL="$(pick_by_git_commit "$ROOT_TRACKED")"
          fi

          if [ -z "$SEL" ]; then
            ANY_TRACKED="$(git ls-files --full-name | awk '/\.zip$/ {print}' || true)"
            if [ -n "${ANY_TRACKED:-}" ]; then
              SEL="$(pick_by_git_commit "$ANY_TRACKED")"
            fi
          fi

          if [ -z "$SEL" ]; then
            SEL="$(ls -1t *.zip 2>/dev/null | head -n1 || true)"
          fi

          if [ -z "$SEL" ]; then
            SEL="$(find . -maxdepth 6 -type f -name '*.zip' -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n1 | cut -d' ' -f2- || true)"
            SEL="${SEL#./}"
          fi

          if [ -z "$SEL" ]; then
            echo "No .zip files found (tracked or untracked)."
            echo "Tip: 把源码 zip 放在仓库根目录，或确保它被 git 追踪。"
            exit 1
          fi

          echo "Picked ZIP: $SEL"
          echo "zip=$GITHUB_WORKSPACE/$SEL" >> "$GITHUB_OUTPUT"

      - name: Unzip project
        shell: bash
        run: |
          unzip -q "${{ steps.pickzip.outputs.zip }}" -d .
          echo "After unzip:"; ls -lah

      - name: Detect project type and root
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          FLUTTER_DIR="$(find . -maxdepth 6 -type f -name pubspec.yaml | head -n1 | xargs -I{} dirname {} || true)"
          GRADLE_DIR=""
          if [ -z "$FLUTTER_DIR" ]; then
            GRADLE_DIR="$(find . -maxdepth 6 -type f \( -name settings.gradle -o -name settings.gradle.kts \) | head -n1 | xargs -I{} dirname {} || true)"
          fi
          if [ -n "$FLUTTER_DIR" ]; then
            echo "project_type=flutter" >> "$GITHUB_OUTPUT"
            echo "project_dir=$FLUTTER_DIR" >> "$GITHUB_OUTPUT"
            echo "Detected Flutter project at: $FLUTTER_DIR"
          elif [ -n "$GRADLE_DIR" ]; then
            echo "project_type=gradle" >> "$GITHUB_OUTPUT"
            echo "project_dir=$GRADLE_DIR" >> "$GITHUB_OUTPUT"
            echo "Detected Android Gradle project at: $GRADLE_DIR"
          else
            echo "❌ 未检测到 Flutter 或 Android Gradle 工程（缺少 pubspec.yaml / settings.gradle）"
            exit 2
          fi

      # ---------- Flutter path ----------
      - name: Set up JDK 17 (for both Flutter & Gradle)
        if: steps.detect.outputs.project_type == 'flutter' || steps.detect.outputs.project_type == 'gradle'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        if: steps.detect.outputs.project_type == 'flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable
          cache: true

      - name: Resolve Flutter deps (pin v2-safe) & pub get
        if: steps.detect.outputs.project_type == 'flutter'
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          rm -rf "$HOME/.pub-cache"
          flutter clean || true
          dart pub remove workmanager || true
          dart pub add workmanager:^0.7.0
          flutter pub get
          echo "== Direct dependencies resolved =="
          flutter pub deps --style=compact | sed -n '/direct dependencies:/,/dev dependencies:/p'
          echo "== .flutter-plugins / .flutter-plugins-dependencies =="
          [ -f .flutter-plugins ] && sed -n '1,200p' .flutter-plugins || true
          [ -f .flutter-plugins-dependencies ] && sed -n '1,200p' .flutter-plugins-dependencies || true
          PUB_CACHE="${PUB_CACHE:-$HOME/.pub-cache}"
          echo "== Scan v1 markers in pub cache =="
          # 更全面的 v1 指纹
          grep -R --include=*.java --include=*.kt -nE \
            'io\.flutter\.app\.(Flutter(Activity|FragmentActivity|Application))|io\.flutter\.view\.FlutterMain|PluginRegistry(\.Registrar)?|registerWith\s*\(|ShimPluginRegistry|GeneratedPluginRegistrant\.registerWith|PluginRegistrantCallback' \
            "$PUB_CACHE" 2>/dev/null || true

      # 1) 清理任何被提交进源码的 GeneratedPluginRegistrant
      - name: Clean ANY checked-in GeneratedPluginRegistrant (Java/Kotlin)
        if: steps.detect.outputs.project_type == 'flutter'
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          find android -type f -regex '.*io/flutter/plugins/GeneratedPluginRegistrant\.\(java\|kt\)$' -print -delete || true

      # 2) 规范 Manifest 为 v2（MainActivity + embedding=2），覆盖 main/debug/profile/flavors
      - name: Normalize all AndroidManifest.xml to v2
        if: steps.detect.outputs.project_type == 'flutter'
        shell: bash
        working-directory: ${{ steps.detect.outputs.project_dir }}
        run: |
          set -euo pipefail
          mapfile -t MANIS < <(find android/app/src -type f -name AndroidManifest.xml)
          for MANI in "${MANIS[@]}"; do
            echo "Normalizing $MANI"
            # 去掉 v1 Application
            sed -i 's/android:name="io\.flutter\.app\.FlutterApplication"[^>]*//g' "$MANI"
            # embedding=2（若不存在则注入在 <application> 后）
            if ! grep -q 'android:name="flutterEmbedding"' "$MANI"; then
              awk '{
                print
              } /<application[^>]*>/ && !i {print "        <meta-data android:name=\"flutterEmbedding\" android:value=\"2\"/>"; i=1}' "$MANI" > "$MANI.__tmp__" && mv "$MANI.__tmp__" "$MANI"
            fi
            # 启动 Activity 显式指向 MainActivity（避免极端误判）
            if grep -q 'android:name="io.flutter.embedding.android.FlutterActivity"' "$MANI"; then
              sed -i 's/android:name="io\.flutter\.embedding\.android\.FlutterActivity"/android:name=".MainActivity"/' "$MANI"
            fi
          done

      # 3) 强化诊断：扫描 app 代码与所有 Manifest
      - name: Deep diagnose v1 markers in app code & manifests
        if: steps.detect.outputs.project_type == 'flutter'
        id: v1scan
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          echo "== Scan android/ (app code) for v1 markers =="
          APP_MATCHES="$(grep -R --include=*.kt --include=*.java -nE \
            'io\.flutter\.app\.(Flutter(Activity|FragmentActivity|Application))|io\.flutter\.view\.FlutterMain|GeneratedPluginRegistrant\.registerWith|PluginRegistry(\.Registrar)?|registerWith\s*\(|ShimPluginRegistry|PluginRegistrantCallback' \
            android 2>/dev/null || true)"
          echo "$APP_MATCHES"
          echo "== Scan ALL AndroidManifest.xml =="
          MANI_MATCHES="$(grep -R -nE 'io\.flutter\.app\.FlutterApplication|android:name=\"io\.flutter\.app\.FlutterApplication\"' android/app/src 2>/dev/null || true)"
          echo "$MANI_MATCHES"
          # 统计命中
          COUNT=0
          [ -n "$APP_MATCHES" ] && COUNT=$((COUNT+1))
          [ -n "$MANI_MATCHES" ] && COUNT=$((COUNT+1))
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"

      # 4) 诊断插件（pub cache），若命中则直接失败（这是真 v1，不可绕）
      - name: Diagnose Android v1 offenders in plugins (fail early)
        if: steps.detect.outputs.project_type == 'flutter'
        working-directory: ${{ steps.detect.outputs.project_dir }}
        shell: bash
        run: |
          set -euo pipefail
          PUB_CACHE="${PUB_CACHE:-$HOME/.pub-cache}"
          MATCHES="$(grep -R --include=*.java --include=*.kt -nE \
            'io\.flutter\.app\.(Flutter(Activity|FragmentActivity|Application))|io\.flutter\.view\.FlutterMain|PluginRegistry(\.Registrar)?|registerWith\s*\(|ShimPluginRegistry|GeneratedPluginRegistrant\.registerWith|PluginRegistrantCallback' \
            "$PUB_CACHE" 2>/dev/null || true)"
          if [ -n "$MATCHES" ]; then
            echo "$MATCHES"
            echo "::error::Found Android v1 embedding inside plugin sources above. Please upgrade/replace those plugins."
            exit 1
          else
            echo "No v1 markers found in plugin sources."
          fi

      # 5) 追加：加固 gitignore，避免未来误提交 GeneratedPluginRegistrant
      - name: Harden .gitignore against GeneratedPluginRegistrant
        if: steps.detect.outputs.project_type == 'flutter'
        shell: bash
        working-directory: ${{ steps.detect.outputs.project_dir }}
        run: |
          set -euo pipefail
          mkdir -p android
          {
            echo ''
            echo '# Ignore Flutter auto-generated registrant (must not be committed)'
            echo 'app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java'
            echo 'app/src/main/kotlin/io/flutter/plugins/GeneratedPluginRegistrant.kt'
          } >> android/.gitignore || true
          tail -n 6 android/.gitignore || true

      - name: Sanity: show project dir & critical files
        if: steps.detect.outputs.project_type == 'flutter'
        shell: bash
        working-directory: ${{ steps.detect.outputs.project_dir }}
        run: |
          pwd
          ls -al android/app/src/main/java/io/flutter/plugins || true
          echo "--- AndroidManifest (main) ---"
          sed -n '1,200p' android/app/src/main/AndroidManifest.xml
          echo "--- AndroidManifest (debug) ---"
          [ -f android/app/src/debug/AndroidManifest.xml ] && sed -n '1,200p' android/app/src/debug/AndroidManifest.xml || true
          echo "--- AndroidManifest (profile) ---"
          [ -f android/app/src/profile/AndroidManifest.xml ] && sed -n '1,200p' android/app/src/profile/AndroidManifest.xml || true

      # 6) （仅在扫描确认 app & manifests 无 v1 痕迹时）临时关闭 flutter_tools 守门员
      - name: TEMP: bypass v1 gate in flutter_tools (CI only; safe after scans)
        if: steps.detect.outputs.project_type == 'flutter' && steps.v1scan.outputs.count == '0'
        shell: bash
        run: |
          set -euo pipefail
          echo "FLUTTER_ROOT = ${FLUTTER_ROOT}"
          TOOLS_DIR="$FLUTTER_ROOT/packages/flutter_tools/lib/src"
          sed -i 's/checkForDeprecation();//' "$TOOLS_DIR/project.dart" || true
          sed -i "s/Build failed due to use of deleted Android v1 embedding\./Bypassed v1 gate in CI./" "$TOOLS_DIR/project.dart" || true

      - name: Build APK (Flutter release)
        if: steps.detect.outputs.project_type == 'flutter'
        run: flutter build apk --release -v
        working-directory: ${{ steps.detect.outputs.project_dir }}

      - name: Upload APK (Flutter)
        if: steps.detect.outputs.project_type == 'flutter'
        uses: actions/upload-artifact@v4
        with:
          name: quote_app-apk
          path: ${{ steps.detect.outputs.project_dir }}/build/app/outputs/flutter-apk/app-release.apk

      # ---------- Gradle path (fallback) ----------
      - name: Set up Gradle 8.4
        if: steps.detect.outputs.project_type == 'gradle'
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Assemble debug with Gradle wrapper
        if: steps.detect.outputs.project_type == 'gradle'
        working-directory: ${{ steps.detect.outputs.project_dir }}
        run: |
          if [[ -x "./gradlew" ]]; then
            ./gradlew assembleDebug
          else
            gradle assembleDebug --no-daemon
          fi

      - name: Upload APK (Gradle)
        if: steps.detect.outputs.project_type == 'gradle'
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            ${{ steps.detect.outputs.project_dir }}/**/outputs/apk/**/*.apk
